,TimeStamp,ETLName,ErrorMessage,StackTrace
3,2002-06-20 06:09:21,CC.UserGroups.v1,"2020-06-02 06:09:21,942 [61] ERROR DynamicEtl.Service - Error with ETL 'CC.UserGroups.v1' - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
4,2002-06-20 06:09:22,UserAccountsWithExtProps.v1,"2020-06-02 06:09:22,852 [43] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
6,2002-06-20 06:29:23,GTXCustomerPopulation.v1,"2020-06-02 06:29:23,124 [11] INFO  DynamicEtl.Service - Value cannot be null.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 146
   at DynamicEtl.Service.Destination.SqlDestinationWriter.Write(IEnumerable`1 data, Int32 batchSize) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Destination\SqlDestinationWriter.cs:line 31
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
"
0,2002-06-20 07:04:37,FidessaMarketMaker.v1,"2020-06-02 07:04:37,577 [81] INFO  DynamicEtl.Service - Cannot open database ""FidessaRaw"" requested by the login. The login failed.","Error Number:4060,State:1,Class:11
   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 146
   at DynamicEtl.Service.Destination.SqlDestinationWriter.Write(IEnumerable`1 data, Int32 batchSize) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Destination\SqlDestinationWriter.cs:line 28
   at DynamicEtl.Service.Destination.SqlMetaProvider.GetMeta() in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Destination\SqlMetaProvider.cs:line 37
   at DynamicEtl.Service.Destination.SqlMetaProvider.getMeta(String connString, String tableName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Destination\SqlMetaProvider.cs:line 62
   at System.Data.SqlClient.SqlConnection.Open()
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
System.Data.SqlClient.SqlException (0x80131904): Cannot open database ""FidessaRaw"" requested by the login. The login failed.
"
8,2002-06-20 07:20:35,InternalTraining.v1,"2020-06-02 07:20:35,863 [34] INFO  DynamicEtl.Service - Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.","Error Number:-2,State:0,Class:11
   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 81
   at DynamicEtl.Service.EtlRunner.RunPostOperations(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 159
   at DynamicEtl.Service.PostOperations.DeleteDuplicateRecords.Execute(Dictionary`2 processInfo, Dictionary`2 mappings) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\PostOperations\DeleteDuplicateRecords.cs:line 38
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
"
1,2002-06-20 07:34:30,GP.Roster.v1,"2020-06-02 07:34:30,364 [23] INFO  DynamicEtl.Service - Invalid column name 'legalEntity'.","Error Number:207,State:1,Class:16
   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 81
   at DynamicEtl.Service.EtlRunner.RunPostOperations(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 159
   at DynamicEtl.Service.PostOperations.StoredProcWithParamPostOperation.Execute(Dictionary`2 info, Dictionary`2 mappings) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\PostOperations\StoredProcWithParamPostOperation.cs:line 64
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'legalEntity'.
"
10,2002-06-20 07:36:10,GEMS.DyEtl.GS.Fidessa.MAEntityLimitsIntraDayAudit.v1,"2020-06-02 07:36:10,241 [91] INFO  DynamicEtl.Service - Value cannot be null.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 146
   at DynamicEtl.Service.Destination.SqlDestinationWriter.Write(IEnumerable`1 data, Int32 batchSize) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Destination\SqlDestinationWriter.cs:line 31
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
"
2,2002-06-20 07:39:17,GP.MetricsRoster.v1,"2020-06-02 07:39:17,437 [23] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
11,2002-06-20 07:39:19,GS.SecurityExceptions.v1,"2020-06-02 07:39:19,799 [63] INFO  DynamicEtl.Service - Value cannot be null.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 81
   at DynamicEtl.Service.EtlRunner.RunPostOperations(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 151
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at DynamicEtl.Service.Factory.BaseOperationsFactory`3.GetOperation(EtlConfig etlConfig, OperationConfig op) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Factory\BaseOperationsFactory.cs:line 34
   at Unity.UnityContainer.Resolve(Type typeToBuild, String nameToBuild, ResolverOverride[] resolverOverrides)
"
14,2002-06-20 07:44:22,GEMS.DyEtl.ExceptionReport.PasswordNeverExpires.v1,"2020-06-02 07:44:22,710 [12] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
19,2002-06-20 07:44:22,GEMS.DyEtl.ExceptionReport.LocalAdminFilter.v1,"2020-06-02 07:44:22,618 [30] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
12,2002-06-20 07:44:23,GEMS.DyEtl.ExceptionReport.Reboot.v1,"2020-06-02 07:44:23,578 [72] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
17,2002-06-20 07:44:23,GEMS.DyEtl.ExceptionReport.NonITAdmin.v1,"2020-06-02 07:44:23,515 [73] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
22,2002-06-20 07:44:25,GEMS.DyEtl.ExceptionReport.RDPFilter.v1,"2020-06-02 07:44:25,718 [13] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
18,2002-06-20 07:44:25,GEMS.DyEtl.ExceptionReport.Website.v1,"2020-06-02 07:44:25,809 [73] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
21,2002-06-20 07:44:26,GEMS.DyEtl.ExceptionReport.AllowPST.v1,"2020-06-02 07:44:26,451 [26] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
20,2002-06-20 07:44:26,GEMS.DyEtl.ExceptionReport.LocalAdmin.v1,"2020-06-02 07:44:26,728 [30] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
15,2002-06-20 07:44:27,GEMS.DyEtl.ExceptionReport.RDP.v1,"2020-06-02 07:44:27,169 [12] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
13,2002-06-20 07:44:28,GEMS.DyEtl.ExceptionReport.ScreensaverTimeout.v1,"2020-06-02 07:44:28,029 [72] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
24,2002-06-20 07:49:09,GEMS.DyEtl.ExceptionReport.MassMedia.v1,"2020-06-02 07:49:09,588 [18] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
25,2002-06-20 07:54:18,GEMS.DyEtl.ExceptionReport.CitrixToLocal.v1,"2020-06-02 07:54:18,523 [69] INFO  DynamicEtl.Service - The remote server returned an error: (500) Internal Server Error.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 79
   at DynamicEtl.Service.EtlRunner.RunPreOperations(EtlConfig etlConfig, String identifier, String arg, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 115
   at DynamicEtl.Service.SourceFetcher.FileVault.FileVaultFetcher.Fetch(String argJson) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\SourceFetcher\FileVault\FileVaultFetcher.cs:line 43
   at System.Net.HttpWebRequest.GetResponse()
"
26,2002-06-20 09:54:19,GS.SecurityExceptions.v1,"2020-06-02 09:54:19,212 [112] INFO  DynamicEtl.Service - Value cannot be null.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 81
   at DynamicEtl.Service.EtlRunner.RunPostOperations(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 151
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at DynamicEtl.Service.Factory.BaseOperationsFactory`3.GetOperation(EtlConfig etlConfig, OperationConfig op) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Factory\BaseOperationsFactory.cs:line 34
   at Unity.UnityContainer.Resolve(Type typeToBuild, String nameToBuild, ResolverOverride[] resolverOverrides)
"
28,2002-06-20 10:24:22,GS.SecurityExceptions.v1,"2020-06-02 10:24:22,831 [60] INFO  DynamicEtl.Service - Value cannot be null.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 81
   at DynamicEtl.Service.EtlRunner.RunPostOperations(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 151
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at DynamicEtl.Service.Factory.BaseOperationsFactory`3.GetOperation(EtlConfig etlConfig, OperationConfig op) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Factory\BaseOperationsFactory.cs:line 34
   at Unity.UnityContainer.Resolve(Type typeToBuild, String nameToBuild, ResolverOverride[] resolverOverrides)
"
31,2002-06-20 12:00:30,GS.SecurityExceptions.v1,"2020-06-02 12:00:30,406 [10] INFO  DynamicEtl.Service - Resolution of the dependency failed, type = 'RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError', name = '(none)'.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 81
   at DynamicEtl.Service.EtlRunner.RunPostOperations(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 151
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at DynamicEtl.Service.Factory.BaseOperationsFactory`3.GetOperation(EtlConfig etlConfig, OperationConfig op) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Factory\BaseOperationsFactory.cs:line 34
   at Unity.UnityContainer.ThrowingBuildUp(IBuilderContext context)
   at Unity.UnityContainer.ThrowingBuildUp(IBuilderContext context)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)
   at lambda_method(Closure , IBuilderContext )
   at RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError..ctor(String destConfig, String configVal)
  Calling constructor RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError(System.String destConfig, System.String configVal)
  Resolving RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError,(none)
Exception occurred while: Calling constructor RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError(System.String destConfig, System.String configVal).
Unity.Exceptions.ResolutionFailedException: Resolution of the dependency failed, type = 'RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError', name = '(none)'.
  Calling constructor RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError(System.String destConfig, System.String configVal)
  Resolving RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError,(none)
Exception occurred while: Calling constructor RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError(System.String destConfig, System.String configVal).
"
30,2002-06-20 12:02:18,GS.SecurityExceptions.v1,"2020-06-02 12:02:18,259 [9] INFO  DynamicEtl.Service - Resolution of the dependency failed, type = 'RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError', name = '(none)'.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 81
   at DynamicEtl.Service.EtlRunner.RunPostOperations(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 151
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at DynamicEtl.Service.Factory.BaseOperationsFactory`3.GetOperation(EtlConfig etlConfig, OperationConfig op) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Factory\BaseOperationsFactory.cs:line 34
   at Unity.UnityContainer.ThrowingBuildUp(IBuilderContext context)
   at Unity.UnityContainer.ThrowingBuildUp(IBuilderContext context)
   at Unity.Strategies.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Unity.ObjectBuilder.BuildPlan.DynamicMethod.DynamicBuildPlanGenerationContext.<>c__DisplayClass16_0.<GetBuildMethod>b__0(IBuilderContext context)
   at lambda_method(Closure , IBuilderContext )
   at RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError..ctor(String destConfig, String configVal)
  Calling constructor RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError(System.String destConfig, System.String configVal)
  Resolving RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError,(none)
Exception occurred while: Calling constructor RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError(System.String destConfig, System.String configVal).
Unity.Exceptions.ResolutionFailedException: Resolution of the dependency failed, type = 'RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError', name = '(none)'.
  Calling constructor RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError(System.String destConfig, System.String configVal)
  Resolving RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError,(none)
Exception occurred while: Calling constructor RiskDashboardEtl.PostOperations.GSSecurityExceptions_OnError(System.String destConfig, System.String configVal).
"
32,2002-06-20 12:17:49,RiskLiquidityOutput.v1,"2020-06-02 12:17:49,500 [40] INFO  DynamicEtl.Service - Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.","To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
Note: There is some performance penalty associated with assembly bind failure logging.
   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 81
   at DynamicEtl.Service.EtlRunner.RunPostOperations(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 159
   at RiskDashboardEtl.PostOperations.RiskLiquidity.Execute(Dictionary`2 info, Dictionary`2 mappings)
"
9,2002-06-20 12:22:40,RiskLiquidityReport.v1,"2020-06-02 12:22:40,798 [34] INFO  DynamicEtl.Service - Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.","To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
Note: There is some performance penalty associated with assembly bind failure logging.
   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 81
   at DynamicEtl.Service.EtlRunner.RunPostOperations(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 159
   at RiskDashboardEtl.PostOperations.RiskLiquidity.Execute(Dictionary`2 info, Dictionary`2 mappings)
"
5,2002-06-20 12:47:43,GEMS.DyEtl.ExceptionReport.MassMedia.v1,"2020-06-02 12:47:43,637 [43] INFO  DynamicEtl.Service - Worksheet with this name is not found.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 132
   at DynamicEtl.Service.DataReader.Excel.ExcelReader.Read(String filepath) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\DataReader\Excel\ExcelReader.cs:line 25
   at DynamicEtl.Service.Extensions.WorkbookExtensions.TryLoadWorksheet(IWorkbook wb, Worksheet& ws, String sheetName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Extensions\WorkbookExtensions.cs:line 13
   at DevExpress.XtraSpreadsheet.API.Native.Implementation.NativeWorksheetCollection.get_Item(String name)
   at DevExpress.Office.Utils.Exceptions.ThrowArgumentOutOfRangeException(String parameterName, String message)
"
27,2002-06-20 12:47:43,GEMS.DyEtl.ExceptionReport.Website.v1,"2020-06-02 12:47:43,511 [44] INFO  DynamicEtl.Service - Worksheet with this name is not found.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 132
   at DynamicEtl.Service.DataReader.Excel.ExcelReader.Read(String filepath) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\DataReader\Excel\ExcelReader.cs:line 25
   at DynamicEtl.Service.Extensions.WorkbookExtensions.TryLoadWorksheet(IWorkbook wb, Worksheet& ws, String sheetName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Extensions\WorkbookExtensions.cs:line 13
   at DevExpress.XtraSpreadsheet.API.Native.Implementation.NativeWorksheetCollection.get_Item(String name)
   at DevExpress.Office.Utils.Exceptions.ThrowArgumentOutOfRangeException(String parameterName, String message)
"
33,2002-06-20 12:47:44,GEMS.DyEtl.ExceptionReport.CitrixToLocal.v1,"2020-06-02 12:47:44,480 [45] INFO  DynamicEtl.Service - Worksheet with this name is not found.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 132
   at DynamicEtl.Service.DataReader.Excel.ExcelReader.Read(String filepath) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\DataReader\Excel\ExcelReader.cs:line 25
   at DynamicEtl.Service.Extensions.WorkbookExtensions.TryLoadWorksheet(IWorkbook wb, Worksheet& ws, String sheetName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Extensions\WorkbookExtensions.cs:line 13
   at DevExpress.XtraSpreadsheet.API.Native.Implementation.NativeWorksheetCollection.get_Item(String name)
   at DevExpress.Office.Utils.Exceptions.ThrowArgumentOutOfRangeException(String parameterName, String message)
"
34,2002-06-20 12:47:44,GEMS.DyEtl.ExceptionReport.AllowPST.v1,"2020-06-02 12:47:44,291 [46] INFO  DynamicEtl.Service - Worksheet with this name is not found.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 132
   at DynamicEtl.Service.DataReader.Excel.ExcelReader.Read(String filepath) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\DataReader\Excel\ExcelReader.cs:line 25
   at DynamicEtl.Service.Extensions.WorkbookExtensions.TryLoadWorksheet(IWorkbook wb, Worksheet& ws, String sheetName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Extensions\WorkbookExtensions.cs:line 13
   at DevExpress.XtraSpreadsheet.API.Native.Implementation.NativeWorksheetCollection.get_Item(String name)
   at DevExpress.Office.Utils.Exceptions.ThrowArgumentOutOfRangeException(String parameterName, String message)
"
36,2002-06-20 12:48:02,GEMS.DyEtl.ExceptionReport.Reboot.v1,"2020-06-02 12:48:02,315 [47] INFO  DynamicEtl.Service - Worksheet with this name is not found.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 132
   at DynamicEtl.Service.DataReader.Excel.ExcelReader.Read(String filepath) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\DataReader\Excel\ExcelReader.cs:line 25
   at DynamicEtl.Service.Extensions.WorkbookExtensions.TryLoadWorksheet(IWorkbook wb, Worksheet& ws, String sheetName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Extensions\WorkbookExtensions.cs:line 13
   at DevExpress.XtraSpreadsheet.API.Native.Implementation.NativeWorksheetCollection.get_Item(String name)
   at DevExpress.Office.Utils.Exceptions.ThrowArgumentOutOfRangeException(String parameterName, String message)
"
35,2002-06-20 12:48:02,GEMS.DyEtl.ExceptionReport.LocalAdminFilter.v1,"2020-06-02 12:48:02,221 [46] INFO  DynamicEtl.Service - Worksheet with this name is not found.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 132
   at DynamicEtl.Service.DataReader.Excel.ExcelReader.Read(String filepath) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\DataReader\Excel\ExcelReader.cs:line 25
   at DynamicEtl.Service.Extensions.WorkbookExtensions.TryLoadWorksheet(IWorkbook wb, Worksheet& ws, String sheetName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Extensions\WorkbookExtensions.cs:line 13
   at DevExpress.XtraSpreadsheet.API.Native.Implementation.NativeWorksheetCollection.get_Item(String name)
   at DevExpress.Office.Utils.Exceptions.ThrowArgumentOutOfRangeException(String parameterName, String message)
"
29,2002-06-20 12:52:41,GEMS.DyEtl.ExceptionReport.LocalAdmin.v1,"2020-06-02 12:52:41,390 [5] INFO  DynamicEtl.Service - Worksheet with this name is not found.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 132
   at DynamicEtl.Service.DataReader.Excel.ExcelReader.Read(String filepath) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\DataReader\Excel\ExcelReader.cs:line 25
   at DynamicEtl.Service.Extensions.WorkbookExtensions.TryLoadWorksheet(IWorkbook wb, Worksheet& ws, String sheetName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Extensions\WorkbookExtensions.cs:line 13
   at DevExpress.XtraSpreadsheet.API.Native.Implementation.NativeWorksheetCollection.get_Item(String name)
   at DevExpress.Office.Utils.Exceptions.ThrowArgumentOutOfRangeException(String parameterName, String message)
"
37,2002-06-20 12:52:41,GEMS.DyEtl.ExceptionReport.RDP.v1,"2020-06-02 12:52:41,038 [4] INFO  DynamicEtl.Service - Worksheet with this name is not found.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 132
   at DynamicEtl.Service.DataReader.Excel.ExcelReader.Read(String filepath) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\DataReader\Excel\ExcelReader.cs:line 25
   at DynamicEtl.Service.Extensions.WorkbookExtensions.TryLoadWorksheet(IWorkbook wb, Worksheet& ws, String sheetName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Extensions\WorkbookExtensions.cs:line 13
   at DevExpress.XtraSpreadsheet.API.Native.Implementation.NativeWorksheetCollection.get_Item(String name)
   at DevExpress.Office.Utils.Exceptions.ThrowArgumentOutOfRangeException(String parameterName, String message)
"
7,2002-06-20 12:52:42,GEMS.DyEtl.ExceptionReport.ScreensaverTimeout.v1,"2020-06-02 12:52:42,467 [11] INFO  DynamicEtl.Service - Worksheet with this name is not found.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 132
   at DynamicEtl.Service.DataReader.Excel.ExcelReader.Read(String filepath) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\DataReader\Excel\ExcelReader.cs:line 25
   at DynamicEtl.Service.Extensions.WorkbookExtensions.TryLoadWorksheet(IWorkbook wb, Worksheet& ws, String sheetName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Extensions\WorkbookExtensions.cs:line 13
   at DevExpress.XtraSpreadsheet.API.Native.Implementation.NativeWorksheetCollection.get_Item(String name)
   at DevExpress.Office.Utils.Exceptions.ThrowArgumentOutOfRangeException(String parameterName, String message)
"
16,2002-06-20 12:52:42,GEMS.DyEtl.ExceptionReport.PasswordNeverExpires.v1,"2020-06-02 12:52:42,116 [12] INFO  DynamicEtl.Service - Worksheet with this name is not found.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 132
   at DynamicEtl.Service.DataReader.Excel.ExcelReader.Read(String filepath) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\DataReader\Excel\ExcelReader.cs:line 25
   at DynamicEtl.Service.Extensions.WorkbookExtensions.TryLoadWorksheet(IWorkbook wb, Worksheet& ws, String sheetName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Extensions\WorkbookExtensions.cs:line 13
   at DevExpress.XtraSpreadsheet.API.Native.Implementation.NativeWorksheetCollection.get_Item(String name)
   at DevExpress.Office.Utils.Exceptions.ThrowArgumentOutOfRangeException(String parameterName, String message)
"
23,2002-06-20 12:52:43,GEMS.DyEtl.ExceptionReport.NonITAdmin.v1,"2020-06-02 12:52:43,967 [13] INFO  DynamicEtl.Service - Worksheet with this name is not found.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 132
   at DynamicEtl.Service.DataReader.Excel.ExcelReader.Read(String filepath) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\DataReader\Excel\ExcelReader.cs:line 25
   at DynamicEtl.Service.Extensions.WorkbookExtensions.TryLoadWorksheet(IWorkbook wb, Worksheet& ws, String sheetName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Extensions\WorkbookExtensions.cs:line 13
   at DevExpress.XtraSpreadsheet.API.Native.Implementation.NativeWorksheetCollection.get_Item(String name)
   at DevExpress.Office.Utils.Exceptions.ThrowArgumentOutOfRangeException(String parameterName, String message)
"
38,2002-06-20 12:57:43,GEMS.DyEtl.ExceptionReport.RDPFilter.v1,"2020-06-02 12:57:43,262 [42] INFO  DynamicEtl.Service - Worksheet with this name is not found.","   at DynamicEtl.Service.EtlRunner.RunJob(String identifier, String arg) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 80
   at DynamicEtl.Service.EtlRunner.RunEtl(EtlConfig etlConfig, String identifier, Dictionary`2 processInfo) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\EtlRunner.cs:line 132
   at DynamicEtl.Service.DataReader.Excel.ExcelReader.Read(String filepath) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\DataReader\Excel\ExcelReader.cs:line 25
   at DynamicEtl.Service.Extensions.WorkbookExtensions.TryLoadWorksheet(IWorkbook wb, Worksheet& ws, String sheetName) in E:\agent\GuggenheimSecurities2018\_work\18\s\src\DynamicEtl.Service\Extensions\WorkbookExtensions.cs:line 13
   at DevExpress.XtraSpreadsheet.API.Native.Implementation.NativeWorksheetCollection.get_Item(String name)
   at DevExpress.Office.Utils.Exceptions.ThrowArgumentOutOfRangeException(String parameterName, String message)
"
